void initCommands(void);
int cd(char *path);
int makedir(char *path);
int remdir(char *path);
int ls(char *path);
int pwd(char *);
int quit(char *);
int help(char *);
int save(char *);
int load(char *);
